services:
  - type: web
    name: report-meta
    env: node
    branch: master
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 